config a10_sata_xcvr_cmupll_core_cfg;
		design a10_sata_xcvr_cmupll_core;
		instance a10_sata_xcvr_cmupll_core.xcvr_cdr_pll_a10_0 use a10_sata_xcvr_cmupll_core_altera_xcvr_cdr_pll_a10_171.altera_xcvr_cdr_pll_a10;
endconfig

