config a10_sata_xcvr_rst_core_cfg;
		design a10_sata_xcvr_rst_core;
		instance a10_sata_xcvr_rst_core.xcvr_reset_control_0 use a10_sata_xcvr_rst_core_altera_xcvr_reset_control_171.altera_xcvr_reset_control;
endconfig

