config a10_sata_xcvr_atxpll_core_cfg;
		design a10_sata_xcvr_atxpll_core;
		instance a10_sata_xcvr_atxpll_core.xcvr_atx_pll_a10_0 use a10_sata_xcvr_atxpll_core_altera_xcvr_atx_pll_a10_171.a10_sata_xcvr_atxpll_core_altera_xcvr_atx_pll_a10_171_pm4bbmq;
endconfig

